jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Bước này sẽ tự cài đặt Gradle vào máy chủ GitHub
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Sau đó gọi lệnh gradle trực tiếp, không cần gradlew nữa
      - name: Build with Gradle
        run: gradle assembleDebug
        
