name: Build Android APK Clean

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Bước tạo Keystore và in mã ra Log
      - name: Generate Permanent Keystore Base64
        run: |
          keytool -genkey -v -keystore my-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias my-alias -storepass 123456 -keypass 123456 -dname "CN=App,O=App,C=VN"
          echo "=== CHUOI BASE64 BAT DAU ==="
          base64 -w 0 my-key.jks
          echo ""
          echo "=== CHUOI BASE64 KET THUC ==="
