      - name: Generate Permanent Keystore Base64
        run: |
          keytool -genkey -v -keystore my-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias my-alias -storepass 123456 -keypass 123456 -dname "CN=App,O=App,C=VN"
          echo "=== CHUOI BASE64 BAT DAU ==="
          base64 -w 0 my-key.jks
          echo ""
          echo "=== CHUOI BASE64 KET THUC ==="
